# -*- coding: utf-8 -*-
"""motivational_chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvBunt_jYKTt9OJxhWneLA1Ix5eEDnyf
"""

import random
import datetime

# List of motivational quotes
quotes = [
    "Believe in yourself and all that you are.",
    "Every day is a second chance.",
    "You are capable of amazing things.",
    "Push yourself, because no one else is going to do it for you.",
    "Difficult roads often lead to beautiful destinations.",
    "Your only limit is your mind."
]

# Time-based greeting
def greet_user():
    hour = datetime.datetime.now().hour
    if hour < 12:
        return "Good morning! ☀️ How are you feeling today?"
    elif hour < 18:
        return "Good afternoon! 😊 How can I support you today?"
    else:
        return "Good evening! 🌙 What’s on your mind?"

# Generate chatbot reply
def get_response(user_input):
    user_input = user_input.lower()
    if "sad" in user_input or "depressed" in user_input:
        return "I'm sorry to hear that. Remember — " + random.choice(quotes)
    elif "tired" in user_input or "exhausted" in user_input:
        return "Rest is important, but don’t forget — " + random.choice(quotes)
    elif "demotivated" in user_input or "lazy" in user_input:
        return "Let me cheer you up — " + random.choice(quotes)
    elif "bye" in user_input:
        return "Take care! You're stronger than you think. 💪"
    else:
        return "I'm here to uplift you. Here's something for you: " + random.choice(quotes)

# Main chat loop
def chatbot():
    print("🤖 Motivational Chatbot")
    print("------------------------")
    print(greet_user())

    while True:
        user_input = input("\nYou: ")
        response = get_response(user_input)
        print("Bot:", response)

        if "bye" in user_input.lower():
            break

# Start chatbot
chatbot()